config/routes.rb
Rails.application.routes.draw do

  root "snapspots#index"
  get "/welcome", to: "welcome#index", as: "welcome"
  resources :users
  resources :snapspots
  # tags
  get 'tags/:tag', to: 'snapspots#index', as: :tag
  # signup
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # login
  get    '/login',   to: 'sessions#new', as:  "login"
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # Fb authentication
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/like', to: 'likes#like', as: "like"
  delete '/unlike', to: 'likes#unlike', as:"unlike"
end

app/models/user.rb
class User < ApplicationRecord
  # associations
  has_many :authentications, dependent: :destroy
  has_many :snapspots, dependent: :destroy
  has_many :likes, dependent: :destroy
  # has_many :comments, dependent: :destroy

  # validations
  has_secure_password
  validates :username, :email, presence: true
  validates :username, :email, uniqueness:true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, length: { minimum:7, maximum:20 }, allow_nil: true
  validates :password_confirmation, confirmation:true, allow_nil:true

  # authentication
  enum access_level: [ :user, :superadmin ]

  #image uploader
  mount_uploader :avatar, ImageUploader

  def capitalize
    self.first_name = self.first_name.capitalize
    self.last_name = self.last_name.capitalize
    self.email = self.email.downcase
  end

  def full_name
    self.first_name + " " + self.last_name
  end

  # returns true of false if a snapspot is liked by user
  def liked?(snapspot)
     self.likes.find_by(snapspot_id: snapspot.id) ? true : false
  end

  # FB
  def self.create_with_auth_and_hash(authentication, auth_hash)

    user = self.create!(
    username: auth_hash["extra"]["raw_info"]["short_name"],
    first_name: auth_hash["extra"]["raw_info"]["first_name"],
    last_name: auth_hash["extra"]["raw_info"]["last_name"],
    email: auth_hash["extra"]["raw_info"]["email"],
    password: SecureRandom.hex(7)
    )
    # This connects the authentication to this user
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end

  def self.authenticate(params)
    user = User.find_by(username:params[:user][:username])
    user.authenticate(params[:user][:password])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.capitalize
    if @user.save
      session[:user_id] = @user.id
      flash.now[:success] = "Account successfully created!"
      redirect_to root_path
    else
      flash.now[:error] = "There was an error creating your account."
      @errors = @user.errors.full_messages
      render template: "users/new"
    end
  end

  def show
    @snapspots = @user.snapspots.paginate(:page => params[:page], :per_page => 9)
  end

  def edit
  end

  def update
    @snapspots = @user.snapspots.paginate(:page => params[:page], :per_page => 9)
    if @user.update_attributes(user_params)
      flash[:success] = "Your details have been updated successfully."
      render template: "users/show"
    else
      @errors = @user.errors.full_messages
      render template: "users/edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:first_name,:last_name,:password,:password_confirmation,:avatar,:created_at,:updated_at,:avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= form.text_field :username, type: 'text', placeholder: "Username" %>
  <%= form.text_field :email, type: 'email', placeholder: "Email address" %>
  <%= form.text_field :first_name, type: 'text', placeholder: "First Name" %>
  <%= form.text_field :last_name, type: 'text', placeholder: "Last Name" %>

app/views/users/_user_snapspots.html.erb
<div class="card-deck">
  <% @snapspots.each do |snapspot| %>
    <%= link_to snapspot_path(snapspot) do %>
      <div class='col-4 my-4'>
        <div class="card text-center">
          <% if snapspot.images.first %>
            <%= image_tag snapspot.images.first.thumb, class: "card-img-top" %>
          <% else %>
            <%= image_tag 'https://s3-ap-southeast-1.amazonaws.com/sammiepls-airbnb-clone/placeholder.png', class: "card-img-top"  %>
          <% end %>
          <div class="card-body">
            <h4 class="card-title"><%= snapspot.name %></h4>
            <p class="card-text"> <%= raw snapspot.tag_list.map { |tag| link_to "##{tag}", tag_path(tag) }.join(" ")  %></p>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<section class="user-hero d-flex align-items-center justify-content-center">
  <h1 class='marker white'>Edit your Profile</h1>
</section>
<main class='container'>
  <div class='row'>
    <div class='col-4'>
      <div class='user-avatar-wrapper'>
        <% if @user.avatar? %>
          <%= image_tag(@user.avatar.thumb.url, class: "user-avatar rounded-circle")  %>
        <% else %>
          <%= image_tag("https://s3-ap-southeast-1.amazonaws.com/sammiepls-snapspot/uploads/anonymous.jpg", class: "user-avatar rounded-circle")  %>
        <% end %>
        <%= form_for @user do |form| %>
          <%= form.file_field :avatar %>
          <%= form.submit class: 'btn-primary', value:"Update Profile Picture" %>
        <% end %>
      </div>
    </div>
    <div class='col-8'>
      <div class='user-edit-form'>
        <%= form_for @user do |form| %>
        <%= render partial: '/users/form', object: form %>

        <div class="my-3">
          <%= form.submit class: 'btn-primary', value:"Update User Details" %>
        </div>
      </div>
  </div>
  <% end %>

</div>
</main>

app/views/users/new.html.erb
<main class='hero'>
  <div class="container">
    <div class="row">
      <div class="col-5 ml-auto mr-auto">
        <div class="hero-login">
          <h1 class='purple'>Sign Up</h1>
          <%= form_for @user do |form| %>

          <%= render partial: '/users/form', object: form %>

            <%= form.password_field :password, placeholder:"Password (must be 7 characters or more)" %>
            <%= form.password_field :password_confirmation, placeholder:"Confirm Password" %>
            <%= form.submit class: 'btn-primary' %>

          <% end %>

          <%= link_to "Sign up with Facebook", "/auth/facebook" %>

        </div>
        <% if @errors %>
          <div class='error-wrapper'>
            <% if @errors.count > 1 %>
              <% @errors.each do |error| %>
                <p><%= error %></p>
              <% end %>
            <% else %>
              <%= @errors %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<section class="user-hero">

</section>
<main class='container'>
  <div class='row'>
    <div class='col-4'>
      <div class='user-avatar-wrapper'>
        <% if @user.avatar? %>
        <%= image_tag(@user.avatar.thumb.url, class: "user-avatar rounded-circle")  %>
        <% else %>
          <%= image_tag("https://s3-ap-southeast-1.amazonaws.com/sammiepls-snapspot/uploads/anonymous.jpg", class: "user-avatar rounded-circle")  %>
        <% end %>
      </div>
    </div>
    <div class='col-8 my-4'>
      <div class='user-details'>
        <h1><%= @user.username %></h1>
        <% if current_user.superadmin? %>
          <%= link_to user_path(@user), method: :delete do %>
            <p><i class='fa fa-fw fa-trash'></i> Delete User
          <% end %>
        <% end %>

        <% if @user == current_user || current_user.superadmin? %>
          <%= link_to edit_user_path(@user) do %>
            <i class='fa fa-fw fa-pencil'></i> Edit User</p>
          <% end %>
        <% end %>

        <p class='mb-0'>Joined since <%= @user.created_at.strftime("%Y-%m-%d") %></p>
        <div class='snapspot-taken'>
          <h4 class='d-inline'>Submitted <%= @user.snapspots.count %></h4>
          <%= image_tag("https://s3-ap-southeast-1.amazonaws.com/sammiepls-snapspot/uploads/snapspot_icon_color.png", class:"d-inline") %>
        </div>
      </div>
    </div>
  </div>

  <div class="row my-4">
    <%= render 'user_snapspots' %>
  </div>
</main>

<%= will_paginate @snapspots %>