config/routes.rb
Rails.application.routes.draw do

  root "snapspots#index"
  get "/welcome", to: "welcome#index", as: "welcome"
  resources :users
  resources :snapspots
  # tags
  get 'tags/:tag', to: 'snapspots#index', as: :tag
  # signup
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # login
  get    '/login',   to: 'sessions#new', as:  "login"
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # Fb authentication
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/like', to: 'likes#like', as: "like"
  delete '/unlike', to: 'likes#unlike', as:"unlike"
end

app/models/snapspot.rb
class Snapspot < ApplicationRecord
  # associations
  belongs_to :user
  has_many :likes, dependent: :destroy
  # has_many :comments, dependent: :destroy

  # validation
  validates :name,:description, presence: true
  validate :address_lat_lng, :must_have_three_tags

  # tags
  acts_as_taggable

  # geocoded
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address

  #image uploader
  mount_uploaders :images, ImageUploader

  def address_lat_lng
    if !address.present? && !latitude.present? && !longitude.present?
      errors.add(:messages, "Address, latitude and longitude can't be blank")
    end
  end

  def must_have_three_tags
    if self.tag_list.count != 3
      errors.add(:messages, "Please supply 3 tags that best describe your SnapSpot")
    end
  end

  def self.search(search)
    if search && !self.tagged_with([search]).empty?
      self.tagged_with([search], :wild => true)
    elsif search
      where('name ILIKE ? OR description ILIKE ?', "%#{search}%","%#{search}%")
    else
      order('id DESC')
    end
  end

end

app/controllers/snapspots_controller.rb
class SnapspotsController < ApplicationController
  before_action :require_login
  before_action :set_snapspot, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Snapspot.tag_counts.order('taggings_count DESC').first(10)
    if params[:tag]
      @snapspots = Snapspot.tagged_with(params[:tag])
    elsif params[:search]
      @snapspots = Snapspot.search(params[:search])
    else
      @snapspots = Snapspot.all.order('updated_at DESC')
    end
    @snapspots = @snapspots.paginate(:page => params[:page], :per_page => 9)
  end

  def new
    @snapspot = Snapspot.new
  end

  def create
    @snapspot = Snapspot.new(snapspot_params)
    if @snapspot.save
      flash.now[:success] = "SnapSpot successfully created!"
      render template: "snapspots/show"
    else
      flash.now[:error] = "There was an error creating your SnapSpot."
      @errors = @snapspot.errors.full_messages
      render template: "snapspots/new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @snapspot.update_attributes(snapspot_params)
      flash[:success] = "Your SnapSpot has been updated successfully."
      redirect_to snapspot_path(@snapspot)
    else
      @errors = @snapspot.errors[:messages].join
      render template: "snapspots/edit"
    end
  end

  def destroy
    @snapspot.destroy
    flash[:success] = 'SnapSpot was successfully deleted'
    redirect_to snapspots_path
  end

  private

  def snapspot_params
    params.require(:snapspot).permit(:user_id, :name, :description, :address, :latitude, :longitude, :created_at,:updated_at,:tag_list, images: [])
  end

  def set_snapspot
    @snapspot = Snapspot.find(params[:id])
  end
end

app/helpers/snapspots_helper.rb
module SnapspotsHelper
end

app/views/snapspots/_form.html.erb
<%= form.hidden_field :user_id, value: current_user.id %>

<div class='row'>
<div class="col-12 my-2">
  <h5><%= form.label :name %></h5>
  <%= form.text_field :name, type: 'text', placeholder: "Name of your SnapSpot!" %>
</div>
<div class="col-12 my-2">
  <h5><%= form.label :description %></h5>
  <%= form.text_area :description, type: 'text_area', placeholder: "Describe your SnapSpot, include how to get there or when is the best time to shoot there" %>
</div>
<div class="col-12 my-2">
  <h5><%= form.label :address %></h5>
  <%= form.text_field :address, type: 'text', placeholder: "Address (optional if you filled in latitude and longitude)" %>
</div>
<div class="col-6 my-2">
  <h5><%= form.label :latitude %></h5>
  <%= form.text_field :latitude, type: 'text', placeholder: "Latitude (optional if you filled in address)" %>
</div>
<div class="col-6 my-2">
  <h5><%= form.label :longitude %></h5>
  <%= form.text_field :longitude, type: 'text', placeholder: "Longitude (optional if you filled in address)" %>
</div>
<div class="col-12 my-2">
  <h5><%= form.label :tag_list %></h5>
  <%= form.text_field :tag_list, type: 'text', placeholder: "List three tags separated by a comma that best describe your SnapSpot. Eg. beach, nature, sand" %>
</div>
<div class='col-12 my-2'>
  <h5>Upload some shots of your awesome SnapSpot!</h5>
  <%= form.file_field :images, multiple: true %>
</div>
</div>

app/views/snapspots/_snapspot_like.html.erb
<% if current_user.liked?(@snapspot) %>
  <%= button_to unlike_path(snapspot_id: @snapspot.id), id:"btn-unlike", remote:true,method: :delete do %>
    <h4 class='purple d-block'><i class='fa fa-heart'></i> <span class="snapspot-like-count"><%= @snapspot.likes.count %></span></h4>
  <% end %>
<% else %>
  <%= button_to like_path(snapspot_id: @snapspot.id),id:"btn-like", remote:true,method: :post do %>
    <h4 class='purple d-block'><i class='fa fa-heart'></i> <span class="snapspot-like-count"><%= @snapspot.likes.count %></span></h4>
  <% end %>
<% end %>

app/views/snapspots/_snapspots.html.erb
<div class="card-deck">

  <% if @snapspots.empty? %>
    <div class='py-5 text-center col-12'>
      <i class='fa fa-frown-o fa-5x mb-3'></i>
      <p>Sorry, there doesn't seem to be anything matching your search </p>
    </div>
  <% else %>
  <% @snapspots.each do |snapspot| %>
    <%= link_to snapspot_path(snapspot) do %>
    <div class='col-4 my-4'>
      <div class="card text-center">
        <% if snapspot.images.first %>
          <%= image_tag snapspot.images.first.polaroid, class: "card-img-top" %>
        <% else %>
          <%= image_tag 'https://s3-ap-southeast-1.amazonaws.com/sammiepls-airbnb-clone/placeholder.png', class: "card-img-top"  %>
        <% end %>
        <div class="card-body">
          <h4 class="card-title"><%= snapspot.name %></h4>
      

          <p class="card-text"> <%= raw snapspot.tag_list.map { |tag| link_to "##{tag}", tag_path(tag) }.join(" ")  %></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Submitted by <%= link_to snapspot.user.username, user_path(snapspot.user) %></small>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  <% end%>

</div>

app/views/snapspots/edit.html.erb
<section class='snapspot-create-hero d-flex align-items-center justify-content-center'>
    <h1 class='marker white'>Edit your SnapSpot</h1>
  </section>
  <% if @errors %>
    <div class='error-wrapper'>
      <%= @errors %>
    </div>
  <% end %>
  <main>
  <div class="container-fluid">
    <div class="row form-bg">
      <div class="col-6">
        <div class='snapspot-form-wrapper'>
          <%= form_for @snapspot do |form| %>
            <%= render partial: '/snapspots/form', object: form %>
            <%= form.submit class: 'btn btn-primary' %>
        </div>
      </div>
      <div class='col-6 pr-0'>
        <div id="map-new" style='width: 100%; height: 100%;'></div>
      </div>
      <% end %>

    </div>
  </div>
</main>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_GEOCODE_KEY'] %>&callback=initMap">
</script>

app/views/snapspots/index.html.erb
<section class="search-wrapper d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-6 ml-auto mr-auto">

        <%= image_tag("https://s3-ap-southeast-1.amazonaws.com/sammiepls-snapspot/uploads/snapspot_icon.png", class: "snapspot-icon")%>
        <%= form_tag snapspots_path, :method => 'get',remote: true, :id => "snapspot_search" do %>
          <%= text_field_tag :search, params[:search], placeholder:"Search for a SnapSpot! Eg. urban, beach, nature..." %>
          <%= button_tag(name:nil,type: "submit", class: "btn-icon mr-2") do %>
            <i class="fa fa-search fa-2x"></i>
          <% end %>
        <% end %>

        <div class='popular-tags pt-3'>
          <h5>Popular Tags</h5>
          <% @tags.each do |tag| %>
          <%= link_to tag.name, tag_path(tag.name) %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</section>

<main class="container my-4">
  <div class="row">
    <div id="snapspot-wrapper">
      <%= render 'snapspots' %>
    </div>
  </div>
</main>


<%= will_paginate @snapspots %>

app/views/snapspots/index.js.erb
$("#snapspot-wrapper").html("<%= escape_javascript(render("snapspots")) %>");

app/views/snapspots/new.html.erb
<section class='snapspot-create-hero d-flex align-items-center justify-content-center'>
    <h1 class='marker white'>Create your SnapSpot</h1>
</section>
  <% if @errors %>
    <div class='error-wrapper'>
      <%= @errors %>
    </div>
  <% end %>
  <main>
  <div class="container-fluid">
    <div class="row form-bg">
      <div class="col-6">
        <div class='snapspot-form-wrapper'>
          <%= form_for @snapspot do |form| %>
            <%= render partial: '/snapspots/form', object: form %>
            <%= form.submit class: 'btn btn-primary' %>
        </div>
      </div>
      <div class='col-6 pr-0'>
        <div id="map-new" style='width: 100%; height: 100%;'></div>

      </div>
      <% end %>

    </div>
  </div>
</main>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_GEOCODE_KEY'] %>&callback=initMap">
    </script>

app/views/snapspots/show.html.erb
<!-- Carousel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <!-- Carousel bullets -->
  <ol class="carousel-indicators">
    <% if @snapspot.images.count > 1 %>
      <% for x in 0..@snapspot.images.count %>
      <% break if x == (@snapspot.images.count) %>
        <% if x == 0 %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= x %>" class="active"></li>
        <% else %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= x %>"></li>
        <% end %>
      <% x += 1 %>
      <% end %>
    <% end %>
  </ol>

  <!-- Carousel -->
  <% if @snapspot.images.first %>
  <div class="carousel-inner" role="listbox" style="z-index:-1; background:url('<%= @snapspot.images.first %>');   background-size: cover;">
  <% else %>
  <div class="carousel-inner" role="listbox" >
  <% end %>
    <div class="carousel-item active">
      <% if @snapspot.images.first %>
      <%= image_tag @snapspot.images.first, class: "snapspot-image d-block img-fluid"  %>
      <% else %>
      <%= image_tag 'https://s3-ap-southeast-1.amazonaws.com/sammiepls-airbnb-clone/placeholder.png', class: "snapspot-image d-block img-fluid"  %>
      <% end %>
    </div>
    <% if @snapspot.images.count > 1 %>
      <% @snapspot.images.shift %>
      <% @snapspot.images.each do |photo| %>
        <div class="carousel-item">
          <%= image_tag photo.url, class: "snapspot-image d-block img-fluid"  %>
        </div>
      <% end %>
  </div>

  <!-- Carousel Controls -->
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <% end %>
</div>

<main>
  <div class="container-fluid offwhite-bg">
    <div class='row'>
      <div class='col-6'>
        <div class='snapspot-user-details p-4'>
          <h1 class='marker'><%= @snapspot.name %></h1>
          <p>Submitted by <%= link_to @snapspot.user.username, user_path(@snapspot.user.username) %></p>
          <% if @snapspot.user == current_user || current_user.superadmin? %>
            <%= link_to snapspot_path(@snapspot), method: :delete do %>
              <p><i class='fa fa-fw fa-trash'></i> Delete SnapSpot
            <% end %>

            <%= link_to edit_snapspot_path(@snapspot) do %>
              <i class='fa fa-fw fa-pencil'></i> Edit SnapSpot</p>
            <% end %>
          <% end %>

          <div id="snapspot-like">
            <%= render 'snapspots/snapspot_like', locals: {snapspot: @snapspot}%>
          </div>

        </div>
        <div class='snapspot-details'>
          <h5>Description</h5>
          <p><%= @snapspot.description %></p>
          <h5>Address</h5>
          <p><%= @snapspot.address %></p>
          <h5>Latitude</h5>
          <p><span id="latitude"><%= @snapspot.latitude %></span></p>
          <h5>Longitude</h5>
          <p><span id="longitude"><%= @snapspot.longitude %></span></p>
          <h5>Tags</h5>
          <%= raw @snapspot.tag_list.map { |tag| link_to "##{tag}", tag_path(tag) }.join(" ")  %>


        </div>
      </div>

      <div class="col-6 pr-0">
        <div style='width: 100%; height:100%;'>
          <div id="show-map" style='width: 100%; height: 100%;'></div>
        </div>
      </div>

    </div>
  </div>
</main>



<script async defer
src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_JS_KEY'] %>&callback=showMap">
</script>