config/routes.rb
Rails.application.routes.draw do

  root "snapspots#index"
  get "/welcome", to: "welcome#index", as: "welcome"
  resources :users
  resources :snapspots
  # tags
  get 'tags/:tag', to: 'snapspots#index', as: :tag
  # signup
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # login
  get    '/login',   to: 'sessions#new', as:  "login"
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # Fb authentication
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/like', to: 'likes#like', as: "like"
  delete '/unlike', to: 'likes#unlike', as:"unlike"
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg sticky-top ">
  <div class='container'>
    <%= link_to root_path do %>
    <% image_tag 'snapspot_logo.svg', class: "logo"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class='fa fa-bars'></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class='navbar-nav ml-auto'>

        <% if logged_in? %>

        <li class="navbar-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SnapSpot
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'View all SnapSpots', snapspots_path, class: "dropdown-item" %>
            <%= link_to 'Create new SnapSpot', new_snapspot_path, class: "dropdown-item" %>
          </div>
        </li>


        <li class="navbar-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'View user profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Edit user profile', edit_user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
        <li class="navbar-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
        <% else %>
        <li class="navbar-item">
          <%= link_to 'Login', login_path, class: "nav-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snapspot</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'snapspot_favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div id="flash">
      <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
      <% end %>
    </div>
    <%= yield %>
    <footer>
      <small>2017 © <%= link_to "Samantha Lau", "https://github.com/sammiepls", class:"white"%></small>
    </footer>
  </body>
</html>